### PR TITLE
Army Crash To Desktop Fix + Minor Cleanup

### PR DESCRIPTION
**Pull request by Jasonleh99**
Submitted a fix for https://github.com/TheOldRealms/TOW_Core/issues/213
=================

Tested this bug on development and it is definitely still a problem. Able to reproduce it 100% of the time with the following steps:
1. Join another lord's army
2. Run command "campaign.ai_raid_village [army leader name] | [village name]"
3. wait for the NPC to finish raiding
4. Crash with a NullPointerException

Crash explanation:
=================
When an NPC finishes raiding a village, I think Bannerlord causes them to "leave" the village, and **Settlement.CurrentSettlement** becomes null before the _village_raid_ended_leaded_by_someone_else_ event fires.
As depicted below, this is a problem because we are calling **Settlement.CurrentSettlement.Culture** without checking for this **null** case.
image

Solution 1
=================
Find the **Settlement** nearest to the player party if **Settlement.CurrentSettlement** is **null** and use that to get the **Culture**.

**Pro**
- Should provide consistent and accurate results every time, we won't have to worry about the wrong culture showing up.

**Con**
- Computationally expensive
- Needs to calculate distance against every settlement unless there is some existing utility by Talesworld

Solution 2
=================
Add a static variable to keep a memo of the player's **Settlement.CurrentSettlement** which is set when the player/army the player is a part of starts raiding a village and use that to get the **Culture** whenever **Settlement.CurrentSettlement** is null.

**Pro**
- Easy to implement
- Relatively consistent, Haven't found a case where the wrong culture shows up with manual testing yet.

**Con**
- Potential edge cases where we show the wrong culture, however not very likely.
- Janky static variable

Current Solution
=================
Currently, I have solution 2 implemented like so
image

Addendum
=================
I also refactored the code for better readability while I was modifying this file.
All I did was separate the nested if statements out and converted our culture checks into switch statements.

### CODE REVIEW

**Comment by Z3rca** [comment]
I am not a big fan of fields or assigned values if they are not absolutely necessary ( and I love dictionaries!). This maybe can produce another kind of side effect which we are currently not aware of. As far as I know, there is a recalculated town distance map ( I forgot the name of the file for it). All in all, I guess the null check of solution 1, is completely sufficient. 

We have way more evil null checks for functions during combat. Which are more frequently called, and be computationally expensive ( I think).  From my unity experience, I am also less a fan of null checks in frequent called methods but it doesn't harm here at the level that it can be problematic I guess. 

I understand the frustration btw, but technically, this event shouldn't be called by Taleworlds to this point, and the responsibility should reside somehow with them.  As I said I would make the null check, explain tale worlds, and maybe one day we take it away since it is not needed anymore. 

I take it away when I completely underestimate the number of calls on this. Did you try out the first solution?

**Comment by Jasonleh99** [comment]
"**I take it away when I completely underestimate the number of calls on this. Did you try out the first solution?**"
I haven't yet, I just didn't feel like doing math last night LOL. It is also my preferred solution though.

Idt this function is called often? at least not often enough to matter. It shouldn't be called for AI parties since this is UI code, and it should only be called when the player does these 3 actions:
1. Raids a village
2. Loots a village
3. Finishes raiding a village as part of another npc's army

I think I found what you're talking about, I went ahead and refactored the solution to find the nearest settlement like so:
image
image

**Comment by Jasonleh99** [comment]
I did also make sure to confirm that the above solution works and fetches the correct nearby settlement*

**Comment by Z3rca** [comment]
From my side okay. Don't know about putting the  Nearest settlement function in the Common functions. Can be merged if nobody else has any problems with it.

**Comment by hunharibo** [comment]
I would skip the search for nearby settlement completely. Reason being is that fetching the nearest settlement is not guaruanteed to return with the same culture than the currently raided settlement is (around kingdom borders).
Just do the null check and set the default background if null. Simple.
Nicely done debugging btw, very professional 👍

**Comment by Jasonleh99** [comment]
"_`Reason being is that fetching the nearest settlement is not guaranteed to return with the same culture than the currently raided settlement is (around kingdom borders).`_"

IIUC this code only ever executes when a player has raided or looted a village, which means that the player party should be right on top of the raided village. The list of settlements we use to calculate for nearest settlements should therefore always return the currently raided settlement and the correct culture.

For example, when raiding Nachthafen village:
image

The nearby settlements within RAID_RADIUS will always grab the raided village (along with others) and then subsequently grab the currently raided village since it should be the closest:
image

I think the only situation where this might be a problem is if another location is almost directly on top of the location being raided.
- If the overlapping location is a hideout, the raid UI would default because the culture wouldn't match up to kingdom cultures
- If the overlapping location is of the same culture, all is well
- If the overlapping location is of a different culture then that's more of a question of like why do we have settlements from two different cultures on top of each other

**Comment by hunharibo** [comment]
You are correct. For some reason I assumed that the raided settlement would be excluded from the search. No further comments. Approved.

**Review by hunharibo — APPROVED** [review]

**Pull request merged**
